"""Added gravatar to User

Revision ID: 81c20bd2a856
Revises: a60d905fa423
Create Date: 2017-10-12 10:43:06.397969

"""

# revision identifiers, used by Alembic.
revision = '81c20bd2a856'
down_revision = 'a60d905fa423'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
