"""Added confirmation to User

Revision ID: a124a022b640
Revises: f93d7e0f8c4c
Create Date: 2017-10-10 08:34:04.187748

"""

# revision identifiers, used by Alembic.
revision = 'a124a022b640'
down_revision = 'f93d7e0f8c4c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
