"""Added gravatar caching

Revision ID: a8ace8440b14
Revises: 81c20bd2a856
Create Date: 2017-10-12 11:01:27.906895

"""

# revision identifiers, used by Alembic.
revision = 'a8ace8440b14'
down_revision = '81c20bd2a856'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    # ### end Alembic commands ###
